EMBEDLY_API_KEY = '7f6cf7cec28511e0866c4040d3dc5c07'


EMBEDLY_INITIAL_DATA = [
    {"type":"html",
     "original_url":"http://t.co/HGLDdZA",
     "url":"http://couch.graphic.ly/post/8481137255/embedding-graphicly-comics-just-got-easy",
     "title":"Embedding Graphicly Comics Just Got Easy",
     "description":"Editor's note: This announcement is largely for publishers and developers, although the benefits reach far beyond these audiences.",
     "favicon_url":"https://i.embed.ly/?url=http%3A//26.media.tumblr.com/avatar_f93350d4d43b_16.png",
     "provider_url":"http://couch.graphic.ly/",
     "provider_display":"couch.graphic.ly",
     "safe":"true",
     "html":"",
     "thumbnail_url":""},
    {"type":"html",
     "original_url":"http://nyti.ms/nneoiY",
     "url":"http://www.nytimes.com/2011/08/09/world/europe/09britain.html?pagewanted=all",
     "title":"Budget Cuts and Scorn for Police Seen Fueling London Riot",
     "description":"LONDON - As London surveyed the damage on Sunday after a small anti-police demonstration spiraled into looting and violence that left 26 police officers injured and led to 55 arrests, many sought to cast the blame beyond the rioters themselves.",
     "favicon_url":"https://i.embed.ly/?url=http%3A//www.nytimes.com/favicon.ico",
     "provider_url":"http://www.nytimes.com/",
     "provider_display":"www.nytimes.com",
     "safe":"true",
     "html":"",
     "thumbnail_url":"https://i.embed.ly/?url=http://graphics8.nytimes.com/images/common/icons/t_wb_75.gif"},
    {"type":"rich",
     "original_url":"http://www.rdio.com/artist/Bon_Iver/album/Bon_Iver/",
     "url":"http://www.rdio.com/artist/Bon_Iver/album/Bon_Iver/",
     "title":"Bon Iver",
     "description":"Bon Iver - Bon Iver. Worth a listen",
     "favicon_url":"https://i.embed.ly/?url=http%3A//ak.rdio.com/media/images/icons/Rdio_48.png",
     "provider_url":"http://www.rdio.com",
     "provider_display":"www.rdio.com",
     "safe":"true",
     "html":"<iframe src=\"https://media.embed.ly/1/frame?wmode=opaque&url=http://www.rdio.com/artist/Bon_Iver/album/Bon_Iver/&height=250&width=500&key=internal&autoplay=true\" width=\"500\" height=\"250\" border=\"0\" scrolling=\"no\" frameborder=\"0\" />",
     "thumbnail_url":"https://i.embed.ly/?url=http%3A//www.rdio.com/_is/%3Fm%3Dalbum/5/d/c/00000000000c7cd5/square-200.jpg%26w%3D200%26h%3D200"},
    {"type":"video",
     "original_url":"http://vimeo.com/18150336",
     "url":"http://vimeo.com/18150336",
     "title":"Wingsuit Basejumping - The Need 4 Speed: The Art of Flight",
     "description":"The Need 4 Speed: The Art of Flight A collection of shots from flights made during the 2009-2010 season by the talented group of wingsuit basejumpers, while flying the V3, Hybrid LD2/Trango rigs and testing several new V-series wingsuit prototypes around Europe.",
     "favicon_url":"http://vimeo.com/favicon.ico",
     "provider_url":"http://vimeo.com/",
     "provider_display":"vimeo.com",
     "safe":"true",
     "html":"<iframe src=\"http://player.vimeo.com/video/18150336?autoplay=1\" width=\"500\" height=\"281\" frameborder=\"0\"></iframe>",
     "thumbnail_url":"http://b.vimeocdn.com/ts/117/311/117311910_1280.jpg"},
    {"type":"html",
     "original_url":"http://techcrunch.com/2011/08/08/yc-funded-snapjoy-will-organize-your-photos-for-you-and-make-sure-you-dont-lose-them/",
     "url":"http://techcrunch.com/2011/08/08/yc-funded-snapjoy-will-organize-your-photos-for-you-and-make-sure-you-dont-lose-them/",
     "title":"YC-Funded Snapjoy Will Organize Your Photos For You (And Make Sure You Don’t Lose Them)",
     "description":"As an intelligent TechCrunch reader with the gift of foresight, you've probably backed up your hard drive — and all of the precious photos locked inside — to at least one cloud service, just in case the unthinkable happens and you lose both your computer and your local backup.",
     "favicon_url":"http://s2.wp.com/wp-content/themes/vip/tctechcrunch2/images/favicon.ico?m=1310283188g",
     "provider_url":"http://techcrunch.com/",
     "provider_display":"techcrunch.com",
     "safe":"true",
     "html":"",
     "thumbnail_url":"http://tctechcrunch2011.files.wordpress.com/2011/08/snapjoyshot.png?w=640"},
    {"type":"html",
     "original_url":"http://www.bbc.co.uk/news/uk-england-london-14450248",
     "url":"http://www.bbc.co.uk/news/uk-england-london-14450248",
     "title":"New violence as May meets police",
     "description":"Home Secretary Theresa May is meeting police chiefs about rioting in London with new violence erupting in Hackney. Skirmishes broke out between police and groups of young people in the area around Mare Street.",
     "favicon_url":"http://www.bbc.co.uk/favicon.ico",
     "provider_url":"http://www.bbc.co.uk/",
     "provider_display":"www.bbc.co.uk",
     "safe":"true",
     "html":"",
     "thumbnail_url":"http://news.bbcimg.co.uk/media/images/54490000/jpg/_54490706_hackney.jpg"},
    {"type":"video",
     "original_url":"http://www.youtube.com/watch?v=xLWpyRAaybU",
     "url":"http://www.youtube.com/watch?v=xLWpyRAaybU",
     "title":"Taylor Swift - Eminem's \"Lose Yourself\" and Uncle Kracker's \"Smile\" Grand Rapids, MI",
     "description":"Taylor rapping Lose Yourself by Eminem then singing \"Smile\" by Uncle Kracker in Grand Rapids Michigan 7-28-11 at Van Andel Arena. All credit to the songs in the video go to the artists, no copyright intended.",
     "favicon_url":"http://s.ytimg.com/yt/favicon-vflZlzSbU.ico",
     "provider_url":"http://www.youtube.com/",
     "provider_display":"www.youtube.com",
     "safe":"true",
     "html":"<object width=\"500\" height=\"306\"><param name=\"wmode\" value=\"opaque\"></param><param name=\"movie\" value=\"http://www.youtube.com/v/xLWpyRAaybU?autoplay=1&version=3\"></param><param name=\"allowFullScreen\" value=\"true\"></param><param name=\"allowscriptaccess\" value=\"always\"></param><embed src=\"http://www.youtube.com/v/xLWpyRAaybU?autoplay=1&version=3\" type=\"application/x-shockwave-flash\" width=\"500\" height=\"306\" allowscriptaccess=\"always\" allowfullscreen=\"true\" wmode=\"opaque\"></embed></object>",
     "thumbnail_url":"http://i1.ytimg.com/vi/xLWpyRAaybU/hqdefault.jpg"}
]
